#!/bin/bash

if [ $(id -u) -eq 0 ]
then
	name=$1
	pass=$2
	daysrnf=$3
	limite=$4
	if cat /etc/passwd |grep $name: |grep -vi [a-z]$name |grep -v [0-9]$name > /dev/null
	then
		echo -e "Erro! O usuario $name ja existe"
	else
		valid=$(date '+%C%y-%m-%d' -d " +$daysrnf days")
		datexp=$(date "+%d/%m/%Y" -d "+ $daysrnf days")
		useradd -M -s /bin/false $name -e $valid
		(echo $pass; echo $pass)|passwd $name 2>/dev/null
		limit $name $limite > /dev/null 2>/dev/null
		echo "<div align='center'>"
echo "<h3>Conta Criada com Sucesso.</h3>"
echo "<p>Login: $1</p>"
echo "<p>Senha: $2</p>"
echo "<p>Proxys portas: 80 e 8080</p>"
echo "<p>Validade: $datexp"
echo "</div>"
	    echo "$pass" > /etc/VpsPackdir/senha/$name
	fi
else
	if echo $(id) |grep sudo > /dev/null
	then
	echo "Seu usuario esta no grupo sudo"
	echo -e "Para virar root execute \033[1;31msudo su\033[0m"
	echo -e "Ou execute o Usercreate como sudo. \033[1;31msudo Usercreate\033[0m"
	else
	echo -e "Vc nao esta como usuario root, nem com seus direitos (sudo)\nPara virar root execute \033[1;31msu\033[0m e digite sua senha root"
	fi
fi
